headerImages = [
  '_static/media/main_menu-IMG/navbar-1.jpg',
  '_static/media/main_menu-IMG/navbar-2.jpg',
  '_static/media/main_menu-IMG/navbar-3.jpg',
  '_static/media/main_menu-IMG/navbar-4.jpg',
  '_static/media/main_menu-IMG/navbar-5.jpg',
  '_static/media/main_menu-IMG/navbar-6.jpg',
  '_static/media/main_menu-IMG/navbar-7.jpg',
  '_static/media/main_menu-IMG/navbar-8.jpg',
  '_static/media/main_menu-IMG/navbar-9.jpg',
]

images = [
  //copy- pasted the same 10 pictures 3 time, did not find a way to re loop trough these after 10.
  '_static/media/home-image-carousel/image-1.jpg',
  '_static/media/home-image-carousel/image-2.jpg',
  '_static/media/home-image-carousel/image-3.jpg',
  '_static/media/home-image-carousel/image-4.jpg',
  '_static/media/home-image-carousel/image-5.jpg',
  '_static/media/home-image-carousel/image-6.jpg',
  '_static/media/home-image-carousel/image-7.jpg',
  '_static/media/home-image-carousel/image-8.jpg',
  '_static/media/home-image-carousel/image-9.jpg',
  '_static/media/home-image-carousel/image-10.jpg',
  '_static/media/home-image-carousel/image-1.jpg',
  '_static/media/home-image-carousel/image-2.jpg',
  '_static/media/home-image-carousel/image-3.jpg',
  '_static/media/home-image-carousel/image-4.jpg',
  '_static/media/home-image-carousel/image-5.jpg',
  '_static/media/home-image-carousel/image-6.jpg',
  '_static/media/home-image-carousel/image-7.jpg',
  '_static/media/home-image-carousel/image-8.jpg',
  '_static/media/home-image-carousel/image-9.jpg',
  '_static/media/home-image-carousel/image-10.jpg',
  '_static/media/home-image-carousel/image-1.jpg',
  '_static/media/home-image-carousel/image-2.jpg',
  '_static/media/home-image-carousel/image-3.jpg',
  '_static/media/home-image-carousel/image-4.jpg',
  '_static/media/home-image-carousel/image-5.jpg',
  '_static/media/home-image-carousel/image-6.jpg',
  '_static/media/home-image-carousel/image-7.jpg',
  '_static/media/home-image-carousel/image-8.jpg',
  '_static/media/home-image-carousel/image-9.jpg',
  '_static/media/home-image-carousel/image-10.jpg'
]
